### PR TITLE
X:line tweaks

### PR DESCRIPTION
**Pull request by Heufneutje**
I made a few changes to the things you've done with the new x:lines. First of all, I fixed a number of typos that snuck in (did you write this code late at night? :P) and I also fixed a numeric that we got wrong and have been getting wrong on every previous version of txircd, according to the RFC.

Lastly I improved the verbosity of the x:line setting messages a bit so that they state the duration again and whether or not they are permament. Just to make sure an oper doesn't accidentally set an x:line with the wrong duration.

There's a problem with the x:line lib you wrote that I sent you a tell about on IRC, but I didn't fix it. The API is kind of your thing so I didn't want to mess with it too much. :P

### CODE REVIEW

**Comment by ElementalAlchemist** [comment]
I (think I) got the notice from Insp, but I'm fine with switching to the YOUREBANNEDCREEP numeric (someone was having a bad day when they wrote the code that named that numeric).

It wasn't late at night, but I did get distracted near the end before I gave up and just kept watching Alex's bonus stream (hence issues with q:line). Some of the other issues come from various code moving/refactoring I did in the middle and apparently didn't fully clean up.

As for your last commit, since "X:Line" no longer starts the sentence, it can be lowercase (e.g. "g:line" instead of "G:Line").

**Comment by Heufneutje** [comment]
The name of that numeric is indeed strange. Also, I usually prefer referring to all of the names with uppercase. Just a personal preference, but if you want I can change it.

**Comment by ElementalAlchemist** [comment]
I've always seen/used them lowercase, and I only capitalized them there because it looks weirder to start the sentence lowercase than it does to capitalize x:line.
I think lowercase is good.

**Comment by Heufneutje** [comment]
Alright. It's been changed. I fixed the typo I found in the x:line lib as well.

**Comment by Heufneutje** [comment]
And I squashed all my typo fix commits a bit for good measure.

**Pull request merged**
