### PR TITLE
Add the xline server notice type

### PR DESCRIPTION
**Pull request by Heufneutje**
Notifies opers of x:lines being set and removed on the local server. I imagine notifying other opers of a ban being set can be quite useful.

### CODE REVIEW

**Comment by ElementalAlchemist** [comment]
I like it.

If you're going to add "addxline" and "removexline" calls to all of the x:line functions, does it not make more sense to add it to the xline library instead? That way you're not repeating yourself everywhere and it's also sent when it's not a local user applying the x:line.

**Comment by Heufneutje** [comment]
I considered that. The only thing that would require is passing a user into the delLine function so you know who removed it. We can probably do that if you'd like though.

**Comment by Heufneutje** [comment]
I'll update my PR when I get back from work.

**Comment by Heufneutje** [comment]
Oh I actually missed the second part of your comment. I kinda feel like we might want to split it for local and remote users the same we have the join and quit notices if we're gonna do that.

**Comment by ElementalAlchemist** [comment]
Users are tied to a server, but x:lines (except for k:lines, which aren't propagated, so it doesn't matter) are globally applicable.
I don't see the value in splitting it into two.

**Comment by Heufneutje** [comment]
Alright. So all I need to do to work it into the base x:line class then is make sure we pass the user that removes an x:line and propagate that through the DELLINE server command as well.

**Comment by Heufneutje** [comment]
And done. Here's the changes that come with this new version:
- The DELLINE server command now takes an additional parameter that contains the hostmask of the user that removed the x:line.
- Sending of the addxline and delxline has been moved to the base x:line class.

**Pull request merged**
