### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Heufneutje**
Apparently this came out today, so we might as well.

### CODE REVIEW

**Comment by ElementalAlchemist** [comment]
Should we do something about the TLS dependencies? (or can we in this file, even?)
http://labs.twistedmatrix.com/2015/04/twisted-1510-released.html

We should probably consider upgrading some of our other old packages as well, e.g. pyopenssl (unless we can have Twisted pull in pyopenssl automatically).

**Comment by Heufneutje** [comment]
The other packages are pretty much up-to-date except for pyopenssl, which I purposely left alone because the newer versions cause issues when I try installing them. I'm all for going with twisted[tls] though.

**Comment by ElementalAlchemist** [comment]
Let's take out `pyopenssl` and replace `twisted` with `twisted[tls]`.

**Comment by Heufneutje** [comment]
It has been done. I wasn't sure whether to include setuptools in our requirements or to just inform the user that it needs to be updated for pyopenssl to build. I decided on the latter.

**Pull request merged**
